'use strict';

angular.module('pguPlayApp').factory('KanjiSrv', function () {

    var kanji = Object.freeze([ //
        ['一', 'ichi'], ['一', 'one'],
        ['二', 'ni'], ['二', 'two'],
        ['三', 'san'], ['三', 'three'],
        ['四', 'yon'], ['四', 'shi'], ['四', 'four'],
        ['五', 'go'], ['五', 'five'],
        ['六', 'roku'], ['六', 'six'],
        ['七', 'shichi'], ['七', 'nana'], ['七', 'seven'],
        ['八', 'hachi'], ['八', 'eight'],
        ['九', 'kyū'], ['九', 'ku'], ['九', 'nine'],
        ['十', 'jū'], ['十', 'ten'],
        ['百', 'hyaku'], ['百', 'hundred'],
        ['千', 'sen'], ['千', 'thousand'],
        ['一万', 'ichi man'], ['一万', 'ten thousand'],
        ['円', 'en'], ['円', 'yen'],
        ['人', 'hito'], ['人', 'person'],
        ['日', 'hi'], ['日', 'Sun'],
        ['月', 'tsuki'], ['月', 'Moon'],
        ['火', 'hi'], ['火', 'fire'],
        ['水', 'mizu'], ['水', 'water'],
        ['木', 'ki'], ['木', 'tree'],
        ['お金', 'okane'], ['お金', 'money'],
        ['土', 'tsuchi'], ['土', 'earth'],
        ['口', 'kuchi'], ['口', 'mouth'],
        ['目', 'me'], ['目', 'eye'],
        ['手', 'te'], ['手', 'hand'],
        ['足', 'ashi'], ['足', 'foot'],
        ['心', 'kokoro'], ['心', 'heart'],
        ['耳', 'mimi'], ['耳', 'ear'],
        ['東', 'higashi'], ['東', 'east'],
        ['西', 'nishi'], ['西', 'west'],
        ['南', 'minami'], ['南', 'south'],
        ['北', 'kita'], ['北', 'north'],
        ['男', 'otoko'], ['男', 'man'],
        ['女', 'onna'], ['女', 'woman'],
        ['子', 'ko'], ['子', 'child'],
        ['父', 'chichi'], ['父', 'father'],
        ['母', 'haha'], ['母', 'mother'],
        ['弟', 'otōto'], ['弟', 'younger bro'],
        ['兄', 'ani'], ['兄', 'elder bro'],
        ['姉', 'ane'], ['姉', 'elder sis'],
        ['妹', 'imōto'], ['妹', 'younger sis'],
        ['山', 'yama'], ['山', 'mountain'],
        ['川', 'kawa'], ['川', 'river'],
        ['田', 'ta'], ['田', 'rice field'],
        ['石', 'ishi'], ['石', 'stone'],
        ['朝', 'asa'], ['朝', 'morning'],
        ['昼', 'hiru'], ['昼', 'noon'],
        ['夜', 'yoru'], ['夜', 'night'],
        ['大きい', 'ookii'], ['大きい', 'big'],
        ['小さい', 'chiisai'], ['小さい', 'small'],
        ['多い', 'ooi'], ['多い', 'many'],
        ['少ない', 'sukunai'], ['少ない', 'few'],
        ['分かる', 'wakaru'], ['分かる', 'to understand'],
        ['年', 'toshi'], ['年', 'year'],
        ['前', 'mae'], ['前', 'before'],
        ['後ろ', 'ushiro'], ['後ろ', 'behind'],
        ['今', 'ima'], ['今', 'now'],
        ['正午', 'shōgo'], ['正午', 'noon'],
        ['時', 'toki'], ['時', 'hour'],
        ['上', 'ue'], ['上', 'up'],
        ['下', 'shita'], ['下', 'under'],
        ['右', 'migi'], ['右', 'right'],
        ['左', 'hidari'], ['左', 'left'],
        ['中', 'naka'], ['中', 'center'],
        ['方', 'hō'], ['方', 'direction'],
        ['元は', 'moto wa'], ['元は', 'originally'],
        ['元気', 'genki'], ['元気', 'healthy'],
        ['文学', 'bungaku'], ['文学', 'literature'],
        ['出る', 'deru'], ['出る', 'to go out'],
        ['入る', 'hairu'], ['入る', 'to go in'],
        ['白い', 'shiroi'], ['白い', 'white'],
        ['赤い', 'akai'], ['赤い', 'red'],
        ['青い', 'aoi'], ['青い', 'blue'],
        ['本', 'hon'], ['本', 'book'],
        ['店', 'mise'], ['店', 'shop'],
        ['学ぶ', 'manabu'], ['学ぶ', 'to learn'],
        ['学校', 'gakkō'], ['学校', 'school'],
        ['先', 'saki'], ['先', 'ahead'],
        ['生', 'nama'], ['生', 'raw'],
        ['会う', 'au'], ['会う', 'to meet'],
        ['社', 'kaisha'], ['社', 'company'],
        ['私', 'watashi'], ['私', 'I'],
        ['高い', 'takai'], ['高い', 'high'],
        ['安い', 'yasui'], ['安い', 'cheap'],
        ['太い', 'futoi'], ['太い', 'fat'],
        ['春', 'haru'], ['春', 'spring'],
        ['夏', 'natsu'], ['夏', 'summer'],
        ['秋', 'aki'], ['秋', 'fall'],
        ['冬', 'fuyu'], ['冬', 'winter'],
        ['半ば', 'nakaba'], ['半ば', 'half'],
        ['間', 'aida'], ['間', 'between'],
        ['道', 'michi'], ['道', 'way'],
        ['車', 'kuruma'], ['車', 'car'],
        ['自ら', 'mizukara'], ['自ら', 'oneself'],
        ['動く', 'ugoku'], ['動く', 'to move'],
        ['近い', 'chikai'], ['近い', 'near'],
        ['遠い', 'tooi'], ['遠い', 'far'],
        ['暑い', 'atsui'], ['暑い', 'hot'],
        ['寒い', 'samui'], ['寒い', 'cold'],
        ['行く', 'iku'], ['行く', 'to go'],
        ['来る', 'kuru'], ['来る', 'to come'],
        ['名前', 'namae'], ['名前', 'name'],
        ['友達', 'tomodachi'], ['友達', 'friend'],
        ['新しい', 'atarashii'], ['新しい', 'new'],
        ['古い', 'furui'], ['古い', 'old'],
        ['強い', 'tsuyoi'], ['強い', 'strong'],
        ['弱い', 'yowai'], ['弱い', 'weak'],
        ['力', 'chikara'], ['力', 'power'],
        ['立', 'tatsu'], ['立', 'to stand up'],
        ['若い', 'wakai'], ['若い', 'young'],
        ['広い', 'hiroi'], ['広い', 'wide'],
        ['悪い', 'warui'], ['悪い', 'bad'],
        ['重い', 'omoi'], ['重い', 'heavy'],
        ['早い', 'hayai'], ['早い', 'early'],
        ['持つ', 'motsu'], ['持つ', 'to hold'],
        ['待つ', 'matsu'], ['待つ', 'to wait'],
        ['買う', 'kau'], ['買う', 'to buy'],
        ['売る', 'uru'], ['売る', 'to sell'],
        ['開ける', 'akeru'], ['開ける', 'to open'],
        ['閉める', 'shimeru'], ['閉める', 'to close'],
        ['始める', 'hajimeru'], ['始める', 'to start'],
        ['終わる', 'owaru'], ['終わる', 'to finish'],
        ['帰る', 'kaeru'], ['帰る', 'to return'],
        ['休む', 'yasumu'], ['休む', 'to rest'],
        ['体', 'karada'], ['体', 'body'],
        ['言う', 'iu'], ['言う', 'to say'],
        ['話す', 'hanasu'], ['話す', 'to talk'],
        ['聞く', 'kiku'], ['聞く', 'to hear'],
        ['書く', 'kaku'], ['書く', 'to write'],
        ['読む', 'yomu'], ['読む', 'to read'],
        ['見る', 'miru'], ['見る', 'to see'],
        ['思う', 'omou'], ['思う', 'to think'],
        ['作る', 'tsukuru'], ['作る', 'to make'],
        ['教える', 'oshieru'], ['教える', 'to teach'],
        ['習う', 'narau'], ['習う', 'to learn'],
        ['使う', 'tsukau'], ['使う', 'to use'],
        ['知る', 'shiru'], ['知る', 'to know'],
        ['雨', 'ame'], ['雨', 'rain'],
        ['病', 'yamai'], ['病', 'illness'],
        ['仕事', 'shigoto'], ['仕事', 'job'],
        ['事', 'koto'], ['事', 'thing'],
        ['若者', 'wakamono'], ['若者', 'young person'],
        ['地図', 'chizu'], ['地図', 'map'],
        ['所', 'tokoro'], ['所', 'place'],
        ['外', 'soto'], ['外', 'outside'],
        ['好き', 'suki'], ['好き', 'like'],
        ['変わる', 'kawaru'], ['変わる', 'to change'],
        ['着る', 'kiru'], ['着る', 'to wear'],
        ['物', 'mono'], ['物', 'object'],
        ['食べる', 'taberu'], ['食べる', 'to eat'],
        ['飲む', 'nomu'], ['飲む', 'to drink'],
        ['国', 'kuni'], ['国', 'country'],
        ['語る', 'kataru'], ['語る', 'to tell'],
        ['空', 'sora'], ['空', 'sky'],
        ['花', 'hana'], ['花', 'flower'],
        ['字', 'ji'], ['字', 'character'],
        ['楽しい', 'tanoshii'], ['楽しい', 'pleasant'],
        ['電気', 'denki'], ['電気', 'electricity'],
        ['明るい', 'akarui'], ['明るい', 'clear'],
        ['家', 'ie'], ['家', 'house']
    ]);

    return {
        kanji: kanji
    };
});